name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t registry.digitalocean.com/mcuve-registry/auth .
      - run: docker login -u $DIGITAL_OCEAN_TOKEN -p $DIGITAL_OCEAN_TOKEN registry.digitalocean.com/mcuve-registry
        env:
          DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - run: docker push registry.digitalocean.com/mcuve-registry/auth
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save mcuve-cluster
      - run: kubectl rollout restart deployment auth-depl
